--!strict

local droneAnimations = {
    throw = {
        path = "Workspace.Dummy With Drone.AnimSaves.Drone Send",
        animationId = "rbxassetid://132035373064086",
        kind = "animation",
    },

    remoteEquip = {
        path = "Workspace.Dummy With Remote.AnimSaves.Power On",
        animationId = "rbxassetid://110067228372695",
        kind = "animation",
    },

    remoteIdle = {
        path = "Workspace.Dummy With Remote.AnimSaves.Idle",
        animationId = "rbxassetid://120343852724268",
        kind = "animation",
    },

    remoteUnequip = {
        path = "Workspace.Dummy With Remote.AnimSaves.Power Off",
        animationId = "rbxassetid://97233937083477",
        kind = "animation",
    },

    leftStickForward = {
        path = "Workspace.Dummy With Remote.AnimSaves.LS Up",
        animationId = "rbxassetid://102669975336940",
        kind = "animation",
    },

    leftStickBackward = {
        path = "Workspace.Dummy With Remote.AnimSaves.LS Down",
        animationId = "rbxassetid://121305239060579",
        kind = "animation",
    },

    leftStickLeft = {
        path = "Workspace.Dummy With Remote.AnimSaves.LS Left",
        animationId = "rbxassetid://106690105064843",
        kind = "animation",
    },

    leftStickRight = {
        path = "Workspace.Dummy With Remote.AnimSaves.LS Right",
        animationId = "rbxassetid://116712588719321",
        kind = "animation",
    },

    rightStickForward = {
        path = "Workspace.Dummy With Remote.AnimSaves.RS Uo",
        animationId = "rbxassetid://120524768248273",
        kind = "animation",
    },

    rightStickBackward = {
        path = "Workspace.Dummy With Remote.AnimSaves.RS Down",
        animationId = "rbxassetid://77263952583258",
        kind = "animation",
    },

    rightStickLeft = {
        path = "Workspace.Dummy With Remote.AnimSaves.RS Left",
        animationId = "rbxassetid://78055173002150",
        kind = "animation",
    },

    rightStickRight = {
        path = "Workspace.Dummy With Remote.AnimSaves.RS Right",
        animationId = "rbxassetid://86661639568668",
        kind = "animation",
    },
}

return droneAnimations

